apiVersion: v1
kind: Service
metadata:
  name: sre-bootcamp-web
  namespace: sre-bootcamp
  labels:
    app: sre-bootcamp-web
spec:
  type: ClusterIP
  selector:
    app: sre-bootcamp-web
  ports:
    - name: http
      port: 8000
      targetPort: http
